### ISSUE TITLE
Revisit touch pins in docs.

### ISSUE THREAD

**Issue by JoelGHI** [ghi-electronics/Docs#123]
Touch pins for G400D in spreadsheet are not included in pinout table in docs.

**Comment by JoelGHI** [comment]
Touch pins for G400D in spreadsheet are not included in pinout table in docs.

**Comment by gus-ghielec** [comment]
Touch, as in resistive touch, is no longer supported in TinyCLR. The world is using capacitive touch now. We will have managed drivers explained instead.
