### ISSUE TITLE
Add ALFAT manual, F40 USB schematic, and other filesystem resources.

### ISSUE THREAD

**Issue by JoelGHI** [ghi-electronics/Docs#138]
Manual:  http://old.ghielectronics.com/downloads/man/File_System_User_Manual.pdf
Schematic was here:  http://old.ghielectronics.com/catalog/product/428
Other resources found here:  http://old.ghielectronics.com/support/file-system

**Comment by Arke64** [comment]
Firmware for uALFAT too

**Comment by Arke64** [comment]
Should be done.
