### ISSUE TITLE
Document automotive category in hardware

### ISSUE THREAD

**Issue by Arke64** [ghi-electronics/Docs#144]
Just talk about our capabilities, move CANxtra there.

**Comment by Arke64** [comment]
CANxtra was moved to the auto page, but more detail is needed.

**Comment by Arke64** [comment]
Looks like the page itself is fine, we just need to fix the space in the two resource links on the page

**Comment by gus-ghielec** [comment]
It says "Display Module: ER-TFT070-4 with capacitive touch panel."

**Comment by Arke64** [comment]
Done in latest push
