### ISSUE TITLE
Update the discovery page

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/Docs#18]
Maybe include nucleo?

**Comment by gus-ghielec** [comment]
I mean pill in the latest branch before checking anything




Regards,




Gus







On Mon, Jul 31, 2017 at 8:44 AM -0400, "John Brochue" <notifications@github.com> wrote:












Assigned #18 to @gus-ghielec.

**Comment by Arke64** [comment]
Done in #20
