### ISSUE TITLE
Explain licensing the various parts of TinyCLR

### ISSUE THREAD

**Issue by Arke64** [ghi-electronics/Docs#184]
Particularly the firmware binary that we provide. Keep the supported devices page in mind.

**Comment by Arke64** [comment]
Empty page at https://docs.ghielectronics.com/software/tinyclr/licensing.html, the site links to it

**Comment by Arke64** [comment]
In particular we need to figure out where to put the license notices for the commercial firmwares. They have things like the networking stack and image decoders that may require attribution.

**Comment by gus-ghielec** [comment]
@Arke64 You say the website links here but I am not seeing it. Please close this issue if no links.

**Comment by Arke64** [comment]
It was on the old porting page which is gone now.
