### ISSUE TITLE
Add more part number info to displays

### ISSUE THREAD

**Issue by Arke64** [ghi-electronics/Docs#233]
Technically the part numbers we list are for the version without touch panels. ER-TFT070-4 for the UD700 needs to also list ER-TPC070-6 as the touch panel part number.

**Comment by gus-ghielec** [comment]
Done

**Comment by Arke64** [comment]
Is it? I'm not seeing it on the page anywhere, just TFT070.

**Comment by Arke64** [comment]
Done in latest push
