### ISSUE TITLE
Broken schematic link

### ISSUE THREAD

**Issue by sielenk** [ghi-electronics/Docs#265]
The "Schematic" link in page https://github.com/ghi-electronics/Docs/blob/master/hardware/gadgeteer/fez-cerbot.md is broken.

The file can still be found in the internet archive at
https://web.archive.org/web/20171011000730/http://files.ghielectronics.com/downloads/Schematics/FEZ/FEZ%20Cerbot%20Schematic.pdf

Maybe add it to this repository instead of linking to ghielectronics.com?

**Comment by gus-ghielec** [comment]
Thanks for pointing this out. We are redoing the entire docs. And yes, the PDF is in the repo instead of external on the new docs.
