### ISSUE TITLE
Need to add Cerb40 II

### ISSUE THREAD

**Issue by Arke64** [ghi-electronics/Docs#51]
To the FEZ Cerberus document

**Comment by gus-ghielec** [comment]
This is identical to Cerb40. no need for an additional pin driver. If a must, make a copy of the one you have.

**Comment by Arke64** [comment]
This is for http://docs.ghielectronics.com/hardware/legacy_products/gadgeteer/fez_cerberus.html not the pins classes. Just the schematic and an image is needed.

**Comment by greg-norris** [comment]
Fixed
