### ISSUE TITLE
Button code example pin assignments are reversed

### ISSUE THREAD

**Issue by dft277** [ghi-electronics/Docs#69]
In MODULES.HTM  the code example for Button the pin assignments are reversed.    
Document indicates  LED on FEZSpider.GpioPin.Socket4.Pin3 
and  Button on FEZSPider.GpioPin.Socket4.Pin4

According to the schematic  the LED is on Pin4 and the button is on Pin3

**Comment by Arke64** [comment]
Thanks for the catch! It's been correct for the next upload.
