### ISSUE TITLE
Better document using NETMF

### ISSUE THREAD

**Issue by Arke64** [ghi-electronics/Docs#70]
Talk about how the latest 4.1 can be found in the 2016 R1 SDK for example.

Add links to the sam-ba and ST DFU tools that the installer requires for them to install manually before the SDK so we can remove the downloads folder on the new GHI site.

Mention the different Visual Studios and that they can still do 4.1 with VS2013.

http://docs.ghielectronics.com/hardware/legacy_products/netmf/intro.html

**Comment by gus-ghielec** [comment]
All tutorials are in and improvements are made to NETMF.
