### ISSUE TITLE
Provide a small managed example to access the file system

### ISSUE THREAD

**Issue by Arke64** [ghi-electronics/Docs#83]

**Comment by Arke64** [comment]
Initial code from Viktor, still in progress.

[SDreader.zip](https://github.com/ghi-electronics/Docs/files/1548373/SDreader.zip)

**Comment by VictorDuma** [comment]
Add functions:
ReadDirectory
WriteToFile
AddFile - cant test.  reason data changed from spi
[SDreader.zip](https://github.com/ghi-electronics/Docs/files/1589866/SDreader.zip)

**Comment by Arke64** [comment]
Give an example using something like http://old.ghielectronics.com/community/codeshare/entry/559 from Taylorza, just a simple RAM system to show how to use the API and read/write a file

**Comment by VictorDuma** [comment]
A little bit tricky without documentation.
class Program
    {
        
        static void Main()
        {
            byte[] data = { 0, 1, 2, 3, 4, 5 };
            byte[] ReadBuf = new byte[6];

            var blockDriver = new MemoryBlockDriver();
            var tfs = new TinyFileSystem(blockDriver);

            tfs.Format();
            tfs.Mount();

            var stream = tfs.Open("GHI", FileMode.CreateNew, 8);

            stream.Write(data, 0, 6);
            stream.Read(ReadBuf, 0, 6);
  
            var file = tfs.GetFiles();
  
            foreach (var i in ReadBuf)
                Debug.WriteLine(i.ToString());


        }
    }

**Comment by Arke64** [comment]
We may add file system itself in 1.0, so this may not be needed.

**Comment by Arke64** [comment]
Since we added filesystem itself, not needed.
